"""initial

Revision ID: 6231d47567aa
Revises:
Create Date: 2026-05-29 14:21:15.449100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6231d47567aa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_storages_name"), "storages", ["name"], unique=True)
    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("storage_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("bitrate_mbps", sa.Float(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("size_mb", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["storage_id"],
            ["storages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        op.f("ix_videos_storage_id"), "videos", ["storage_id"], unique=False
    )
    op.create_table(
        "probes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("download_speed_mbps", sa.Float(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("Healthy", "Warning", "Critical", name="probe_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_probes_created_at"), "probes", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_probes_video_id"), "probes", ["video_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_probes_video_id"), table_name="probes")
    op.drop_index(op.f("ix_probes_created_at"), table_name="probes")
    op.drop_table("probes")
    op.drop_index(op.f("ix_videos_storage_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_storages_name"), table_name="storages")
    op.drop_table("storages")
    # ### end Alembic commands ###
