"""is_bad field in videos

Revision ID: a74e5a752ce5
Revises: 7c8b60078761
Create Date: 2026-06-02 12:40:36.128642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a74e5a752ce5"
down_revision: Union[str, Sequence[str], None] = "7c8b60078761"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos",
        sa.Column(
            "errors_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.execute("UPDATE videos SET errors_count = 0 WHERE errors_count IS NULL")

    op.add_column("videos", sa.Column("last_error_date", sa.DateTime(), nullable=True))
    op.add_column(
        "videos",
        sa.Column(
            "is_bad",
            sa.Boolean(),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "is_bad")
    op.drop_column("videos", "last_error_date")
    op.drop_column("videos", "errors_count")
    # ### end Alembic commands ###
