name: CI/CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  IMAGE_NAME: citadelbv/pb-accessibility-analysis

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 -U test_user -d test_db && exit 0
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

          echo "PostgreSQL did not start in time"
          exit 1
        env:
          PGPASSWORD: test_pass

      - name: Run tests
        env:
          MODE: TEST

          AUTH_USER: test
          AUTH_PASS: test

          REDIS_DSN: redis://localhost:6379/0
          DB_USER: test_user
          DB_ENGINE: "postgresql+asyncpg"
          DB_PASSWORD: test_pass
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_NAME: test_db

        run: |
          uv run pytest tests \
            -v \
            --cov=app \
            --cov-report=term-missing

  deploy:
    needs: test

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            citadelbv/video-monitor-v2:latest
            citadelbv/video-monitor-v2:${{ github.sha }}

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}

          script: |
            cd /opt/video-monitor-v2

            cat > .env <<EOF
            MODE=PROD

            AUTH_USER=${{ secrets.AUTH_USER }}
            AUTH_PASS=${{ secrets.AUTH_PASS }}

            DB_ENGINE=postgresql+asyncpg
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}

            REDIS_DSN=${{ secrets.REDIS_DSN }}

            VIDEO_MIN_SIZE_MB=${{ secrets.VIDEO_MIN_SIZE_MB }}
            VIDEOS_DOWNLOAD_SIZE_MB=${{ secrets.VIDEOS_DOWNLOAD_SIZE_MB }}

            MIN_BASELINE_SPEED_MBPS=${{ secrets.MIN_BASELINE_SPEED_MBPS }}
            MONITORING_RUN_INTERVAL_MINUTES=${{ secrets.MONITORING_RUN_INTERVAL_MINUTES }}

            ANALYTICS_UPDATE_INTERVAL_MINUTES=${{ secrets.ANALYTICS_UPDATE_INTERVAL_MINUTES }}

            KVS_CV=${{ secrets.KVS_CV }}
            KVS_AHV=${{ secrets.KVS_AHV }}
            IP=${{ secrets.IP }}
            EOF
            
            cd pb-accessibility-analysis
            
            docker compose pull

            docker compose down

            docker compose up -d